### ISSUE TITLE
Getting this to work on OpenBSD 7.2 (snapshot) 

### ISSUE THREAD

**Issue by BSDNix** [toxyl/ossh#28]
Right now the Golang version on OpenBSD struggles with 

`./fake_shell_overlayfs.go:290:15: undefined: unix.Mount`
`./fake_shell_overlayfs.go:306:45: undefined: syscall.MNT_DETACH`

This has to do with the overlayFS is what Docker uses, and Docker does not work (natively) on OpenBSD. 

To make Docker work on OpenBSD there has to be a VM/VMD running with Alpine that runs Docker. Performance may be flakey but i can always try to make that working.

I'll keep you updated with that project.

**Comment by toxyl** [comment]
I haven't heard anything back, so I'm closing this issue. Feel free to reopen it..
